/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Backend.CheckValidation;
import com.github.lgooddatepicker.components.DatePicker;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Gia Naicker
 */
public class Student extends javax.swing.JFrame {

    private CheckValidation validator;

    private boolean isNameValid = true;
    private boolean isSurnameValid = true;
    private boolean isIdValid = true;
    private boolean isEmailValid = true;

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        setLocationRelativeTo(null);

        validator = new CheckValidation();

        ButtonGroup radioButtons = new ButtonGroup();
        radioButtons.add(yesRadioButton);
        radioButtons.add(noRadioButton);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        registerStudentLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idNumberLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        validateRegistrationButton = new javax.swing.JButton();
        idNumberTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        dobDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        gradeSpinner = new javax.swing.JSpinner();
        schoolEmailLabel = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        gradeErrorMessageLabel = new javax.swing.JLabel();
        nameErrorMessageLabel = new javax.swing.JLabel();
        surnameErrorMessageLabel = new javax.swing.JLabel();
        schoolEmailErrorMessageLabel = new javax.swing.JLabel();
        dobErrorMessageLabel = new javax.swing.JLabel();
        idNumberErrorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        registerStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerStudentLabel.setText("Register as a student");
        registerStudentLabel.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        registerStudentLabel.setForeground(new java.awt.Color(0, 0, 0));

        surnameLabel.setText("Surname");
        surnameLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        surnameLabel.setForeground(new java.awt.Color(0, 0, 0));

        nameLabel.setText("Name");
        nameLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 0, 0));

        idNumberLabel.setText("ID Number");
        idNumberLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        idNumberLabel.setForeground(new java.awt.Color(0, 0, 0));

        gradeLabel.setText("Grade");
        gradeLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(0, 0, 0));

        dobLabel.setText("Date Of Birth");
        dobLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(0, 0, 0));

        validateRegistrationButton.setText("Validate Registration");
        validateRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateRegistrationButtonActionPerformed(evt);
            }
        });

        idNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNumberTextFieldActionPerformed(evt);
            }
        });
        idNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idNumberTextFieldKeyReleased(evt);
            }
        });

        nameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });
        surnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                surnameTextFieldKeyReleased(evt);
            }
        });

        gradeSpinner.setModel(new javax.swing.SpinnerNumberModel(8, 8, 12, 1));
        gradeSpinner.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N

        schoolEmailLabel.setText("Do you have a school email");
        schoolEmailLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        schoolEmailLabel.setForeground(new java.awt.Color(0, 0, 0));

        yesRadioButton.setText("yes");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setText("no");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(validateRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(surnameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dobDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surnameErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(nameErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idNumberErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dobErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gradeSpinner))
                            .addComponent(schoolEmailLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(yesRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(noRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(schoolEmailErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gradeErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(registerStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(registerStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNumberErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gradeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gradeErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(schoolEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesRadioButton)
                            .addComponent(noRadioButton)))
                    .addComponent(schoolEmailErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(validateRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNumberTextFieldActionPerformed
        dobDatePicker.requestFocus();
    }//GEN-LAST:event_idNumberTextFieldActionPerformed

    private void yesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioButtonActionPerformed
        yesRadioButton.setSelected(true);
        noRadioButton.setSelected(false);
    }//GEN-LAST:event_yesRadioButtonActionPerformed

    private void validateRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateRegistrationButtonActionPerformed
        String name = nameTextField.getText();
        String surname = surnameTextField.getText();
        String id = idNumberTextField.getText();
        LocalDate dob = dobDatePicker.getDate();
        int grade = (int) gradeSpinner.getValue();

        //Presence check for name
        if (!validator.presenceCheck(name)) {
            isNameValid = false;
            nameTextField.setBackground(Color.red);
            nameErrorMessageLabel.setForeground(Color.red);
            nameErrorMessageLabel.setText("Please enter a name");
        } else {
            isNameValid = true;
            nameErrorMessageLabel.setText("");
        }

        //Presence check for surname
        if (!validator.presenceCheck(surname)) {
            surnameTextField.setBackground(Color.red);
            surnameErrorMessageLabel.setForeground(Color.red);
            surnameErrorMessageLabel.setText("Please enter a surname");
        } else {
            isSurnameValid = true;
            surnameErrorMessageLabel.setText("");
        }

        //Presence check for id
        if (!validator.presenceCheck(id)) {
            isIdValid = false;
            idNumberTextField.setBackground(Color.red);
            idNumberErrorMessageLabel.setForeground(Color.red);
            idNumberErrorMessageLabel.setText("Please enter an ID Number");
        } else {
            isIdValid = true;
            idNumberErrorMessageLabel.setText("");
        }

        //Handles ID and dob error
        if (!validator.checkIDandDOB(id, dob)) {
            dobDatePicker.setBackground(Color.red);
            dobErrorMessageLabel.setForeground(Color.red);
            dobErrorMessageLabel.setText("Your ID and date of birth do not correspond");
            isNameValid = false;
        } else {
            dobDatePicker.setBackground(Color.white);
            dobErrorMessageLabel.setText("");
            isNameValid = true;
        }

        //Handles age and grade error
        if (!validator.ageGradeLogicCheck(dob, grade)) {
            dobDatePicker.setBackground(Color.red);
            gradeErrorMessageLabel.setForeground(Color.red);
            gradeErrorMessageLabel.setText("Your age does not correspond with your current grade.");
        } else {
            dobDatePicker.setBackground(Color.white);
            gradeErrorMessageLabel.setText("");
        }

        //Handles radio button errors
        if (!yesRadioButton.isSelected() && !noRadioButton.isSelected()) {
            schoolEmailErrorMessageLabel.setForeground(Color.red);
            schoolEmailErrorMessageLabel.setText("Please select either yes or no");
            isEmailValid = false;
        } else {
            schoolEmailErrorMessageLabel.setText("");
            isEmailValid = true;
        }

        if (isNameValid && isSurnameValid && isIdValid && isIdValid && isEmailValid
                && validator.ageGradeLogicCheck(dob, grade)
                && validator.checkIDandDOB(id, dob)) {

            JOptionPane.showMessageDialog(null, "Your registration was successful", "Confirmation Message", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_validateRegistrationButtonActionPerformed

    private void noRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioButtonActionPerformed
        noRadioButton.setSelected(true);
        yesRadioButton.setSelected(false);
    }//GEN-LAST:event_noRadioButtonActionPerformed

    private void surnameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameTextFieldKeyReleased
        String surname = surnameTextField.getText();

        if (!validator.presenceCheck(surname)) {
            surnameTextField.setBackground(Color.red);
            surnameErrorMessageLabel.setForeground(Color.red);
            isSurnameValid = false;
            surnameErrorMessageLabel.setText("Please enter a surname");
        } else if (!validator.checkString(surname)) {
            surnameTextField.setBackground(Color.red);
            surnameErrorMessageLabel.setForeground(Color.red);
            surnameErrorMessageLabel.setText("Surname cannot contain digits/characters");
            isSurnameValid = false;
        } else {
            surnameTextField.setBackground(Color.white);
            surnameErrorMessageLabel.setText("");
            isSurnameValid = true;

        }
    }//GEN-LAST:event_surnameTextFieldKeyReleased

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        idNumberTextField.requestFocus();
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    private void idNumberTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idNumberTextFieldKeyReleased
        String id = idNumberTextField.getText();

        if (!validator.presenceCheck(id)) {
            idNumberTextField.setBackground(Color.red);
            idNumberErrorMessageLabel.setForeground(Color.red);
            idNumberErrorMessageLabel.setText("Please enter an ID Number");
            isIdValid = false;
        } else if (!validator.checkDigit(id)) {
            idNumberTextField.setBackground(Color.red);
            idNumberErrorMessageLabel.setForeground(Color.red);
            idNumberErrorMessageLabel.setText("ID cannot contain special characters");
            isIdValid = false;
        } else if (!validator.checkLength(id)) {
            idNumberTextField.setBackground(Color.red);
            idNumberErrorMessageLabel.setForeground(Color.red);
            idNumberErrorMessageLabel.setText("The ID must be 13 digits");
            isIdValid = false;
        } else {
            idNumberTextField.setBackground(Color.white);
            idNumberErrorMessageLabel.setText("");
            isIdValid = true;
        }
    }//GEN-LAST:event_idNumberTextFieldKeyReleased

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
        String name = nameTextField.getText();
        if (!validator.presenceCheck(name)) {
            nameTextField.setBackground(Color.red);
            nameErrorMessageLabel.setForeground(Color.red);
            nameErrorMessageLabel.setText("Please enter a name");
            isNameValid = false;
        } else if (!validator.checkString(name)) {
            nameTextField.setBackground(Color.red);
            nameErrorMessageLabel.setForeground(Color.red);
            nameErrorMessageLabel.setText("Name cannot contain digits/characters");
            isNameValid = false;
        } else {
            nameTextField.setBackground(Color.white);
            nameErrorMessageLabel.setText("");
            isNameValid = true;
        }
    }//GEN-LAST:event_nameTextFieldKeyReleased

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        surnameTextField.requestFocus();
    }//GEN-LAST:event_nameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker dobDatePicker;
    private javax.swing.JLabel dobErrorMessageLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.ButtonGroup emailButtonGroup;
    private javax.swing.JLabel gradeErrorMessageLabel;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JSpinner gradeSpinner;
    private javax.swing.JLabel idNumberErrorMessageLabel;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JTextField idNumberTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameErrorMessageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JLabel registerStudentLabel;
    private javax.swing.JLabel schoolEmailErrorMessageLabel;
    private javax.swing.JLabel schoolEmailLabel;
    private javax.swing.JLabel surnameErrorMessageLabel;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JButton validateRegistrationButton;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
